#!/usr/bin/env node
/*
Merge Node (c8) and Browser (Istanbul) coverage into a unified report.
Steps:
1. Read all JSON coverage objects from coverage/browser/*.json (if any)
2. Read c8 JSON summary from coverage/coverage-final.json (generated by c8)
3. Merge maps using istanbul-lib-coverage
4. Generate:
   - coverage/merged/coverage-final.json (combined JSON)
   - coverage/merged/lcov.info (LCOV)
   - coverage/merged/html/ (HTML report)
Usage:
  node tools/merge_coverage.js
*/

const fs = require('fs');
const path = require('path');
const { createCoverageMap } = require('istanbul-lib-coverage');
const report = require('istanbul-lib-report');
const reports = require('istanbul-reports');

function readJsonIfExists(p) {
  if (!fs.existsSync(p)) return null;
  try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return null; }
}

function loadBrowserCoverage(dir) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const f of fs.readdirSync(dir)) {
    if (!f.endsWith('.json')) continue;
    const data = readJsonIfExists(path.join(dir, f));
    if (data) out.push(data);
  }
  return out;
}

function main() {
  const root = process.cwd();
  const nodeCovPath = path.join(root, 'coverage', 'coverage-final.json');
  const browserDir = path.join(root, 'coverage', 'browser');
  const mergedDir = path.join(root, 'coverage', 'merged');
  fs.mkdirSync(mergedDir, { recursive: true });

  const nodeCov = readJsonIfExists(nodeCovPath);
  const browserCovList = loadBrowserCoverage(browserDir);

  if (!nodeCov && browserCovList.length === 0) {
    console.log('No coverage data found (node or browser). Nothing to merge.');
    return;
  }

  const map = createCoverageMap({});
  if (nodeCov) map.merge(nodeCov);
  for (const b of browserCovList) map.merge(b);

  // Write merged JSON
  const mergedJsonPath = path.join(mergedDir, 'coverage-final.json');
  fs.writeFileSync(mergedJsonPath, JSON.stringify(map.toJSON()));

  // Generate LCOV + HTML
  const context = report.createContext({ dir: mergedDir, coverageMap: map });
  const lcovReport = reports.create('lcovonly');
  const htmlReport = reports.create('html');
  lcovReport.execute(context);
  htmlReport.execute(context);

  console.log('Merged coverage written to:', mergedJsonPath);
  console.log('LCOV:', path.join(mergedDir, 'lcov.info'));
  console.log('HTML report dir:', path.join(mergedDir, 'index.html'));
}

main();
